testing script

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -81,35 +81,33 @@ jobs:
         Environment: ${{secrets.Environment}}
         AWSAccountID: ${{secrets.AWSAccountID}}
         InstanceType: ${{secrets.InstanceType}}
-        Monitoring: ${{secrets.Monitoring}}    
+        Monitoring: ${{secrets.Monitoring}}
+        stack_name: "prueba-coca"
+        template_url: "https://cfnprueba.s3.amazonaws.com/template.txt"    
       run: |  
-       chmod +x ./ghactions-scripts/deploy.sh
+       if ! update_output=$(aws cloudformation update-stack --stack-name "$stack_name" --template-url "$template_url" --parameters ParameterKey=InstanceType,ParameterValue=$InstanceType ParameterKey=Monitoring,ParameterValue=$Monitoring 2>&1); then
+          if [[ $update_output == *"No updates are to be performed."* ]]; then
+            echo "No updates needed for the stack."
+          elif [[ $update_output == *"An error occurred (ValidationError) when calling the UpdateStack operation: Stack ["$stack_name"] does not exist"* ]]; then
+            aws cloudformation create-stack --stack-name "$stack_name" --template-url "$template_url" --parameters ParameterKey=InstanceType,ParameterValue=$InstanceType ParameterKey=Monitoring,ParameterValue=$Monitoring
+            aws cloudformation wait stack-create-complete --stack-name "$stack_name"
+          else
+            echo "Update failed: $update_output"
+            exit 1
+          fi
+       else
+          echo "Stack update was executed. Update in progress..."
+          aws cloudformation wait stack-update-complete --stack-name "$stack_name"
+       fi
 
-       ./ghactions-scripts/deploy.sh prueba-coca https://cfnprueba.s3.amazonaws.com/template.txt ParameterKey=InstanceType ParameterValue=$InstanceType ParameterKey=Monitoring ParameterValue=$Monitoring 
-
-      #  if ! update_output=$(aws cloudformation update-stack --stack-name "$stack_name" --template-url "$template_url" --parameters ParameterKey=InstanceType,ParameterValue=$InstanceType 2>&1); then
-      #     if [[ $update_output == *"No updates are to be performed."* ]]; then
-      #       echo "No updates needed for the stack."
-      #     elif [[ $update_output == *"An error occurred (ValidationError) when calling the UpdateStack operation: Stack ["$stack_name"] does not exist"* ]]; then
-      #       aws cloudformation create-stack --stack-name "$stack_name" --template-url "$template_url" --parameters ParameterKey=InstanceType,ParameterValue=$InstanceType
-      #       aws cloudformation wait stack-create-complete --stack-name "$stack_name"
-      #     else
-      #       echo "Update failed: $update_output"
-      #       exit 1
-      #     fi
-      #  else
-      #     echo "Stack update was executed. Update in progress..."
-      #     aws cloudformation wait stack-update-complete --stack-name "$stack_name"
-      #  fi
-
-      #  stack_status=$(aws cloudformation describe-stacks --stack-name "$stack_name" --query "Stacks[0].StackStatus" --output text)
+       stack_status=$(aws cloudformation describe-stacks --stack-name "$stack_name" --query "Stacks[0].StackStatus" --output text)
        
-      #  if [[ $stack_status != "CREATE_COMPLETE" && $stack_status != "UPDATE_COMPLETE" ]]; then
-      #     echo "Current status: $stack_status"
-      #     exit 1
-      #  else
-      #     echo "Current status: $stack_status."
-      #  fi
+       if [[ $stack_status != "CREATE_COMPLETE" && $stack_status != "UPDATE_COMPLETE" ]]; then
+          echo "Current status: $stack_status"
+          exit 1
+       else
+          echo "Current status: $stack_status."
+       fi
 
 
     # - name: Deploy Infraestructure - project-template
